app.cors.allowed-origins=http://localhost:3000,http://${NETWORK}:3000

# ===============================================
# CONFIGURACION DEL FRONTEND
# ===============================================
# URL base donde corre tu aplicacion frontend (sin la barra final)
app.frontend.base-url=http://localhost:3000