# Configuracion para AWS
server.use-forward-headers=true
server.port=80


app.cors.allowed-origins=http://reacciona-frontend-alb-534253633.us-east-1.elb.amazonaws.com,https://reacciona-frontend-alb-534253633.us-east-1.elb.amazonaws.com

# ===============================================
# CONFIGURACION DEL FRONTEND para el envio del correo de cambio de clave
# ===============================================
app.frontend.base-url=http://reacciona-frontend-alb-534253633.us-east-1.elb.amazonaws.com